version: 1
theme: "EfCherie"
margin: 0
custom_themes:
  - scheme: "TokyoNight"
    author: "noctalia-theme-sync"
    base00: "1a1b26"
    base01: "24283b"
    base02: "3b4261"
    base03: "545c7e"
    base04: "6d77aa"
    base05: "c0caf5"
    base06: "dae8fc"
    base07: "e0af68"
    base08: "f7768e"
    base09: "ff9e64"
    base0A: "e0af68"
    base0B: "9ece6a"
    base0C: "7dcfff"
    base0D: "7aa2f7"
    base0E: "bb9af7"
    base0F: "c099ff"
  - scheme: "EfCherie"
    author: "noctalia-theme-sync"
    base00: "190a0f"
    base01: "2a1520"
    base02: "3d2030"
    base03: "6a4a5a"
    base04: "9a7a8a"
    base05: "d3cfcf"
    base06: "e8e0e0"
    base07: "f0d1d5"
    base08: "d07080"
    base09: "e09070"
    base0A: "d0a060"
    base0B: "90b870"
    base0C: "80c0a0"
    base0D: "b0a0d0"
    base0E: "d07080"
    base0F: "a06070"
